/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.MessageManager;
import Model.Socket.getObject;
import View.Table.TicketTableClient;
import java.io.IOException;

/**
 *
 * @author Arthur Novikov
 */
public class TicketView extends javax.swing.JDialog {

    TicketTableClient ticketTable;
    /**
     * Creates new form Ticket
     * @param flight
     * @throws java.io.IOException
     * @throws java.lang.ClassNotFoundException
     */
    public TicketView(int flight) throws IOException, ClassNotFoundException {
        ticketTable = new TicketTableClient(flight);
        initComponents();
        setModal(true);
        setLocationRelativeTo(null);
        table.removeColumn(table.getColumnModel().getColumn(0));
    }
    
    public void setTickets(getObject obj) {
        ticketTable.setTickets(obj);
        table.updateUI();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        number = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        series = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        fio = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        cost = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setSize(new java.awt.Dimension(500, 300));

        addButton.setText("Добавить");
        addButton.setDoubleBuffered(true);
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        updateButton.setText("Изменить");
        updateButton.setDoubleBuffered(true);
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        deleteButton.setText("Удалить");
        deleteButton.setDoubleBuffered(true);
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        jScrollPane1.setDoubleBuffered(true);

        table.setModel(ticketTable);
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        number.setDoubleBuffered(true);

        jLabel4.setText("Номер паспорта:");
        jLabel4.setDoubleBuffered(true);

        jLabel3.setText("Серия паспорта:");
        jLabel3.setDoubleBuffered(true);

        series.setDoubleBuffered(true);

        jLabel2.setText("ФИО пассажира:");
        jLabel2.setDoubleBuffered(true);

        fio.setDoubleBuffered(true);

        jLabel1.setText("Цена билета:");
        jLabel1.setDoubleBuffered(true);

        cost.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(addButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(number, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(series)
                            .addComponent(fio, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
                            .addComponent(cost)))
                    .addComponent(jScrollPane1))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(fio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(series, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(number, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addButton)
                    .addComponent(updateButton)
                    .addComponent(deleteButton)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        try {
            if (fio.getText().equals(""))
                MessageManager.Error("Не указаны ФИО пассажира");
            ticketTable.add((int) cost.getValue(), fio.getText(),
                Integer.parseInt(series.getText()), Integer.parseInt(number.getText()));
            table.updateUI();
        }
        catch (NumberFormatException e) {
            MessageManager.Error("Серия и номер паспорта должны быть заданы в числовом формате");
        }
        catch (NullPointerException e) {
            MessageManager.checkAllFields();
        }
        catch (Exception e) {
            MessageManager.Error(e.getMessage());
        }
    }//GEN-LAST:event_addButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        try {
            ticketTable.update((int) table.getModel().getValueAt(table.getSelectedRow(), 0),
                (int) cost.getValue(), fio.getText(),
                Integer.parseInt(series.getText()), Integer.parseInt(number.getText()));
            table.updateUI();
        }
        catch (NumberFormatException e) {
            MessageManager.Error("Серия и номер паспорта должны быть заданы в числовом формате");
        }
        catch (NullPointerException e) {
            MessageManager.checkAllFields();
        }
        catch (Exception e) {
            MessageManager.Error(e.getMessage());
        }
    }//GEN-LAST:event_updateButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        try {
            if (table.getSelectedRow() != -1 && table.getSelectedRow() < table.getRowCount()) {
                ticketTable.delete((int) table.getModel().getValueAt(table.getSelectedRow(), 0));
                table.updateUI();
            }
        }
        catch (Exception e) {
            MessageManager.Error(e.getMessage());
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        try {
            cost.setValue(table.getModel().getValueAt(table.getSelectedRow(), 1));
            fio.setText((String) table.getModel().getValueAt(table.getSelectedRow(), 2));
            series.setText((table.getModel().getValueAt(table.getSelectedRow(), 3)).toString());
            number.setText(table.getModel().getValueAt(table.getSelectedRow(), 4).toString());
        }
        catch (Exception e) {
            MessageManager.Error(e.getMessage());
        }
    }//GEN-LAST:event_tableMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JSpinner cost;
    private javax.swing.JButton deleteButton;
    private javax.swing.JTextField fio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField number;
    private javax.swing.JTextField series;
    private javax.swing.JTable table;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}